services:
  - type: web
    name: personal-study-map
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir src app:app"
    plan: free
    autoDeploy: true
